[workspace]
resolver = "2"
members = ["agent","api", "common"]

[workspace.package]
edition = "2024"
license = "Apache-2.0"

[workspace.dependencies]
anyhow = "1.0.102"
async-trait = "0.1.89"
axum = { version = "0.8.8", features = ["macros"] }
clap = { version = "4.5.60", features = ["derive", "env"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.6.8", features = ["cors", "request-id", "trace", "validate-request"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "json"] }
utoipa = "5.4.0"

lucid-common = { path = "./common" }
